### ISSUE TITLE
Hey bro, how do you decrypt dis files?

### ISSUE THREAD

**Issue by Maulana-XD** [KhanhNguyen9872/Convert_Marshal-PYC#2]
0           0 RESUME                   0

   1           2 NOP

   2           4 LOAD_CONST               0 (0)
               6 LOAD_CONST               1 (None)
               8 IMPORT_NAME              0 (re)
              10 STORE_NAME               0 (re)
              12 LOAD_CONST               0 (0)
              14 LOAD_CONST               1 (None)
              16 IMPORT_NAME              1 (os)
              18 STORE_NAME               1 (os)
              20 LOAD_CONST               0 (0)
              22 LOAD_CONST               1 (None)
              24 IMPORT_NAME              2 (sys)
              26 STORE_NAME               2 (sys)
              28 LOAD_CONST               0 (0)

**Comment by KhanhNguyen9872** [comment]
> 0 0 RESUME 0
> 
> 1 2 NOP
> 
> 2 4 LOAD_CONST 0 (0) 6 LOAD_CONST 1 (None) 8 IMPORT_NAME 0 (re) 10 STORE_NAME 0 (re) 12 LOAD_CONST 0 (0) 14 LOAD_CONST 1 (None) 16 IMPORT_NAME 1 (os) 18 STORE_NAME 1 (os) 20 LOAD_CONST 0 (0) 22 LOAD_CONST 1 (None) 24 IMPORT_NAME 2 (sys) 26 STORE_NAME 2 (sys) 28 LOAD_CONST 0 (0)

just view it, this opcode is
```python3
import re
import os
import sys
```

**Comment by Maulana-XD** [comment]
> > 0 0 RESUME 0
> > 1 2 NOP
> > 2 4 LOAD_CONST 0 (0) 6 LOAD_CONST 1 (None) 8 IMPORT_NAME 0 (re) 10 STORE_NAME 0 (re) 12 LOAD_CONST 0 (0) 14 LOAD_CONST 1 (None) 16 IMPORT_NAME 1 (os) 18 STORE_NAME 1 (os) 20 LOAD_CONST 0 (0) 22 LOAD_CONST 1 (None) 24 IMPORT_NAME 2 (sys) 26 STORE_NAME 2 (sys) 28 LOAD_CONST 0 (0)
> 
> just view it, this opcode is
> 
> ```python
> import re
> import os
> import sys
> ```

**Comment by Maulana-XD** [comment]
> > 0 0 RESUME 0
> > 1 2 NOP
> > 2 4 LOAD_CONST 0 (0) 6 LOAD_CONST 1 (None) 8 IMPORT_NAME 0 (re) 10 STORE_NAME 0 (re) 12 LOAD_CONST 0 (0) 14 LOAD_CONST 1 (None) 16 IMPORT_NAME 1 (os) 18 STORE_NAME 1 (os) 20 LOAD_CONST 0 (0) 22 LOAD_CONST 1 (None) 24 IMPORT_NAME 2 (sys) 26 STORE_NAME 2 (sys) 28 LOAD_CONST 0 (0)
> 
> just view it, this opcode is
> 
> ```python
> import re
> import os
> import sys
> ```

What if it's like this?

0           0 RESUME                   0

  1           2 LOAD_CONST               0 (0)
              4 LOAD_CONST               1 (None)
              6 IMPORT_NAME              0 (os)
              8 STORE_NAME               0 (os)
             10 LOAD_CONST               0 (0)
             12 LOAD_CONST               1 (None)
             14 IMPORT_NAME              1 (re)
             16 STORE_NAME               1 (re)
             18 LOAD_CONST               0 (0)
             20 LOAD_CONST               1 (None)
             22 IMPORT_NAME              2 (requests)
             24 STORE_NAME               2 (requests)
             26 LOAD_CONST               0 (0)
             28 LOAD_CONST               1 (None)
             30 IMPORT_NAME              3 (json)
             32 STORE_NAME               3 (json)
             34 LOAD_CONST               0 (0)
             36 LOAD_CONST               1 (None)
             38 IMPORT_NAME              4 (bs4)
             40 STORE_NAME               4 (bs4)

  2          42 LOAD_CONST               0 (0)
             44 LOAD_CONST               2 (('BeautifulSoup',))
             46 IMPORT_NAME              4 (bs4)
             48 IMPORT_FROM              5 (BeautifulSoup)
             50 STORE_NAME               6 (parser)
             52 POP_TOP

  3          54 PUSH_NULL
             56 LOAD_NAME                2 (requests)
             58 LOAD_ATTR                7 (Session)
             68 PRECALL                  0
             72 CALL                     0
             82 STORE_NAME               8 (ses)

  5          84 LOAD_CONST               3 (<code object login at 0x7666933e00, file "", line 5>)
             86 MAKE_FUNCTION            0
             88 STORE_NAME               9 (login)

 19          90 LOAD_CONST               4 (<code object menu at 0x7666936400, file "", line 19>)
             92 MAKE_FUNCTION            0
             94 STORE_NAME              10 (menu)

 44          96 PUSH_NULL
             98 LOAD_NAME               10 (menu)
            100 PRECALL                  0
            104 CALL                     0
            114 POP_TOP
            116 LOAD_CONST               1 (None)
            118 RETURN_VALUE

Disassembly of <code object login at 0x7666933e00, file "", line 5>:
  5           0 RESUME                   0

  6           2 LOAD_GLOBAL              1 (NULL + os)
             14 LOAD_ATTR                1 (system)
             24 LOAD_CONST               1 ('clear')
             26 PRECALL                  1
             30 CALL                     1
             40 POP_TOP

  7          42 LOAD_GLOBAL              5 (NULL + input)
             54 LOAD_CONST               2 (' masukan cookie : ')
             56 PRECALL                  1
             60 CALL                     1
             70 STORE_FAST               0 (cookie)

  8          72 NOP

  9          74 LOAD_GLOBAL              6 (ses)
             86 LOAD_METHOD              4 (get)
            108 LOAD_CONST               3 ('https://business.facebook.com/business_locations')
            110 LOAD_CONST               4 ('Mozilla/5.0 (Linux; Android 8.1.0; MI 8 Build/OPM1.171019.011) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.86 Mobile Safari/537.36')
            112 LOAD_CONST               5 ('https://www.facebook.com/')
            114 LOAD_CONST               6 ('business.facebook.com')
            116 LOAD_CONST               7 ('https://business.facebook.com')
            118 LOAD_CONST               8 ('1')
            120 LOAD_CONST               9 ('id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7')
            122 LOAD_CONST              10 ('max-age=0')
            124 LOAD_CONST              11 ('text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8')
            126 LOAD_CONST              12 ('text/html; charset=utf-8')
            128 LOAD_CONST              13 (('user-agent', 'referer', 'host', 'origin', 'upgrade-insecure-requests', 'accept-language', 'cache-control', 'accept', 'content-type'))
            130 BUILD_CONST_KEY_MAP      9
            132 LOAD_CONST              14 ('cookie')
            134 LOAD_FAST                0 (cookie)
            136 BUILD_MAP                1
            138 KW_NAMES                15
            140 PRECALL                  3
            144 CALL                     3
            154 STORE_FAST               1 (data)

 10         156 LOAD_GLOBAL             11 (NULL + re)
            168 LOAD_ATTR                6 (search)
            178 LOAD_CONST              16 ('(EAAG\\w+)')
            180 LOAD_FAST                1 (data)
            182 LOAD_ATTR                7 (text)
            192 PRECALL                  2
            196 CALL                     2
            206 STORE_FAST               2 (find_token)

 11         208 LOAD_GLOBAL             17 (NULL + open)
            220 LOAD_CONST              17 ('token.txt')
            222 LOAD_CONST              18 ('w')
            224 PRECALL                  2
            228 CALL                     2
            238 LOAD_METHOD              9 (write)
            260 LOAD_FAST                2 (find_token)
            262 LOAD_METHOD             10 (group)
            284 LOAD_CONST              19 (1)
            286 PRECALL                  1
            290 CALL                     1
            300 PRECALL                  1
            304 CALL                     1
            314 POP_TOP

 12         316 LOAD_GLOBAL             17 (NULL + open)
            328 LOAD_CONST              20 ('cookie.txt')
            330 LOAD_CONST              18 ('w')
            332 PRECALL                  2
            336 CALL                     2
            346 LOAD_METHOD              9 (write)
            368 LOAD_FAST                0 (cookie)
            370 PRECALL                  1
            374 CALL                     1
            384 POP_TOP

 13         386 LOAD_GLOBAL             23 (NULL + menu)
            398 PRECALL                  0
            402 CALL                     0
            412 POP_TOP
            414 LOAD_CONST               0 (None)
            416 RETURN_VALUE
        >>  418 PUSH_EXC_INFO

 14         420 POP_TOP

 15         422 LOAD_GLOBAL              1 (NULL + os)
            434 LOAD_ATTR                1 (system)
            444 LOAD_CONST              21 ('rm token.txt cookie.txt')
            446 PRECALL                  1
            450 CALL                     1
            460 POP_TOP

 16         462 LOAD_GLOBAL             25 (NULL + exit)
            474 LOAD_CONST              22 (' login gagal kemungkinan cookie invalid atau tumbal mati')
            476 PRECALL                  1
            480 CALL                     1
            490 POP_TOP
            492 POP_EXCEPT
            494 LOAD_CONST               0 (None)
            496 RETURN_VALUE
        >>  498 COPY                     3
            500 POP_EXCEPT
            502 RERAISE                  1
ExceptionTable:
  74 to 412 -> 418 [0]
  418 to 490 -> 498 [1] lasti

Disassembly of <code object menu at 0x7666936400, file "", line 19>:
 19           0 RESUME                   0

 20           2 NOP

 21           4 LOAD_GLOBAL              1 (NULL + open)
             16 LOAD_CONST               1 ('token.txt')
             18 LOAD_CONST               2 ('r')
             20 PRECALL                  2
             24 CALL                     2
             34 LOAD_METHOD              1 (read)
             56 PRECALL                  0
             60 CALL                     0
             70 STORE_FAST               0 (token)

 22          72 LOAD_GLOBAL              1 (NULL + open)
             84 LOAD_CONST               3 ('cookie.txt')
             86 LOAD_CONST               2 ('r')
             88 PRECALL                  2
             92 CALL                     2
            102 LOAD_METHOD              1 (read)
            124 PRECALL                  0
            128 CALL                     0
            138 STORE_FAST               1 (cok)

 23         140 LOAD_CONST               4 ('cookie')
            142 LOAD_FAST                1 (cok)
            144 BUILD_MAP                1
            146 STORE_FAST               2 (cookie)

 24         148 LOAD_GLOBAL              4 (ses)
            160 LOAD_METHOD              3 (get)
            182 LOAD_CONST               5 ('https://graph.facebook.com/me?fields=name&access_token=')
            184 LOAD_FAST                0 (token)
            186 FORMAT_VALUE             0
            188 BUILD_STRING             2
            190 LOAD_FAST                2 (cookie)
            192 KW_NAMES                 6
            194 PRECALL                  2
            198 CALL                     2
            208 LOAD_METHOD              4 (json)
            230 PRECALL                  0
            234 CALL                     0
            244 LOAD_CONST               7 ('name')
            246 BINARY_SUBSCR
            256 STORE_FAST               3 (nama)
            258 JUMP_FORWARD            21 (to 302)
        >>  260 PUSH_EXC_INFO

 25         262 POP_TOP

 26         264 LOAD_GLOBAL             11 (NULL + login)
            276 PRECALL                  0
            280 CALL                     0
            290 POP_TOP
            292 POP_EXCEPT
            294 JUMP_FORWARD             3 (to 302)
        >>  296 COPY                     3
            298 POP_EXCEPT
            300 RERAISE                  1

 27     >>  302 LOAD_GLOBAL             13 (NULL + print)
            314 LOAD_CONST               8 (' selamat datang ')
            316 LOAD_FAST                3 (nama)
            318 FORMAT_VALUE             0
            320 LOAD_CONST               9 (', silahkan pakai sesuka hati')
            322 BUILD_STRING             3
            324 PRECALL                  1
            328 CALL                     1
            338 POP_TOP

 28         340 LOAD_GLOBAL             15 (NULL + input)
            352 LOAD_CONST              10 (' masukan link : ')
            354 PRECALL                  1
            358 CALL                     1
            368 STORE_FAST               4 (idt)

 29         370 LOAD_GLOBAL             17 (NULL + int)
            382 LOAD_GLOBAL             15 (NULL + input)
            394 LOAD_CONST              11 (' masukan limit : ')
            396 PRECALL                  1
            400 CALL                     1
            410 PRECALL                  1
            414 CALL                     1
            424 STORE_FAST               5 (limit)

 30         426 NOP

 31         428 LOAD_CONST              12 (0)
            430 STORE_FAST               6 (n)

 32         432 LOAD_CONST              13 ('graph.facebook.com')
            434 LOAD_CONST              14 ('max-age=0')
            436 LOAD_CONST              15 ('?0')
            438 LOAD_CONST              16 ('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.66 Safari/537.36')
            440 LOAD_CONST              17 (('authority', 'cache-control', 'sec-ch-ua-mobile', 'user-agent'))
            442 BUILD_CONST_KEY_MAP      4
            444 STORE_FAST               7 (header)

 33         446 LOAD_GLOBAL             19 (NULL + range)
            458 LOAD_GLOBAL             17 (NULL + int)
            470 LOAD_FAST                5 (limit)
            472 PRECALL                  1
            476 CALL                     1
            486 PRECALL                  1
            490 CALL                     1
            500 GET_ITER
        >>  502 FOR_ITER               109 (to 722)
            504 STORE_FAST               8 (x)

 34         506 LOAD_FAST                6 (n)
            508 LOAD_CONST              18 (1)
            510 BINARY_OP               13 (+=)
            514 STORE_FAST               6 (n)

 35         516 LOAD_GLOBAL              4 (ses)
            528 LOAD_METHOD             10 (post)
            550 LOAD_CONST              19 ('https://graph.facebook.com/v16.0/me/feed?link=')
            552 LOAD_FAST                4 (idt)
            554 FORMAT_VALUE             0
            556 LOAD_CONST              20 ('&published=0&access_token=')
            558 LOAD_FAST                0 (token)
            560 FORMAT_VALUE             0
            562 BUILD_STRING             4
            564 LOAD_FAST                7 (header)
            566 LOAD_FAST                2 (cookie)
            568 KW_NAMES                21
            570 PRECALL                  3
            574 CALL                     3
            584 LOAD_ATTR               11 (text)
            594 STORE_FAST               9 (post)

 36         596 LOAD_GLOBAL              9 (NULL + json)
            608 LOAD_ATTR               12 (loads)
            618 LOAD_FAST                9 (post)
            620 PRECALL                  1
            624 CALL                     1
            634 STORE_FAST              10 (data)

 37         636 LOAD_CONST              22 ('id')
            638 LOAD_FAST                9 (post)
            640 CONTAINS_OP              0
            642 POP_JUMP_FORWARD_IF_FALSE    23 (to 690)

 38         644 LOAD_GLOBAL             13 (NULL + print)
            656 LOAD_CONST              23 (' ')
            658 LOAD_FAST                6 (n)
            660 FORMAT_VALUE             0
            662 LOAD_CONST              24 ('. berhasil membagikan ')
            664 LOAD_FAST                5 (limit)
            666 FORMAT_VALUE             0
            668 LOAD_CONST              25 (" ['id']")
            670 BUILD_STRING             5
            672 PRECALL                  1
            676 CALL                     1
            686 POP_TOP
            688 JUMP_BACKWARD           94 (to 502)

 40     >>  690 LOAD_GLOBAL             27 (NULL + exit)
            702 LOAD_CONST              26 (' gagal membagikan, kemungkinan token invalid')
            704 PRECALL                  1
            708 CALL                     1
            718 POP_TOP
            720 JUMP_BACKWARD          110 (to 502)

 33     >>  722 LOAD_CONST               0 (None)
            724 RETURN_VALUE
        >>  726 PUSH_EXC_INFO

 41         728 POP_TOP

 42         730 LOAD_GLOBAL             27 (NULL + exit)
            742 LOAD_CONST              26 (' gagal membagikan, kemungkinan token invalid')
            744 PRECALL                  1
            748 CALL                     1
            758 POP_TOP
            760 POP_EXCEPT
            762 LOAD_CONST               0 (None)
            764 RETURN_VALUE
        >>  766 COPY                     3
            768 POP_EXCEPT
            770 RERAISE                  1
ExceptionTable:
  4 to 256 -> 260 [0]
  260 to 290 -> 296 [1] lasti
  428 to 720 -> 726 [0]
  726 to 758 -> 766 [1] lasti

**Comment by KhanhNguyen9872** [comment]
> masukan

too long, it will waste time, Youtube can teach you

**Comment by KhanhNguyen9872** [comment]
> > > 0 0 RESUME 0
> > > 1 2 NOP
> > > 2 4 LOAD_CONST 0 (0) 6 LOAD_CONST 1 (None) 8 IMPORT_NAME 0 (re) 10 STORE_NAME 0 (re) 12 LOAD_CONST 0 (0) 14 LOAD_CONST 1 (None) 16 IMPORT_NAME 1 (os) 18 STORE_NAME 1 (os) 20 LOAD_CONST 0 (0) 22 LOAD_CONST 1 (None) 24 IMPORT_NAME 2 (sys) 26 STORE_NAME 2 (sys) 28 LOAD_CONST 0 (0)
> > 
> > 
> > just view it, this opcode is
> > ```python
> > import re
> > import os
> > import sys
> > ```
> 
> What if it's like this?
> 
> 0 0 RESUME 0
> 
> 1 2 LOAD_CONST 0 (0) 4 LOAD_CONST 1 (None) 6 IMPORT_NAME 0 (os) 8 STORE_NAME 0 (os) 10 LOAD_CONST 0 (0) 12 LOAD_CONST 1 (None) 14 IMPORT_NAME 1 (re) 16 STORE_NAME 1 (re) 18 LOAD_CONST 0 (0) 20 LOAD_CONST 1 (None) 22 IMPORT_NAME 2 (requests) 24 STORE_NAME 2 (requests) 26 LOAD_CONST 0 (0) 28 LOAD_CONST 1 (None) 30 IMPORT_NAME 3 (json) 32 STORE_NAME 3 (json) 34 LOAD_CONST 0 (0) 36 LOAD_CONST 1 (None) 38 IMPORT_NAME 4 (bs4) 40 STORE_NAME 4 (bs4)
> 
> 2 42 LOAD_CONST 0 (0) 44 LOAD_CONST 2 (('BeautifulSoup',)) 46 IMPORT_NAME 4 (bs4) 48 IMPORT_FROM 5 (BeautifulSoup) 50 STORE_NAME 6 (parser) 52 POP_TOP
> 
> 3 54 PUSH_NULL 56 LOAD_NAME 2 (requests) 58 LOAD_ATTR 7 (Session) 68 PRECALL 0 72 CALL 0 82 STORE_NAME 8 (ses)
> 
> 5 84 LOAD_CONST 3 (<code object login at 0x7666933e00, file "", line 5>) 86 MAKE_FUNCTION 0 88 STORE_NAME 9 (login)
> 
> 19 90 LOAD_CONST 4 (<code object menu at 0x7666936400, file "", line 19>) 92 MAKE_FUNCTION 0 94 STORE_NAME 10 (menu)
> 
> 44 96 PUSH_NULL 98 LOAD_NAME 10 (menu) 100 PRECALL 0 104 CALL 0 114 POP_TOP 116 LOAD_CONST 1 (None) 118 RETURN_VALUE
> 
> Disassembly of <code object login at 0x7666933e00, file "", line 5>: 5 0 RESUME 0
> 
> 6 2 LOAD_GLOBAL 1 (NULL + os) 14 LOAD_ATTR 1 (system) 24 LOAD_CONST 1 ('clear') 26 PRECALL 1 30 CALL 1 40 POP_TOP
> 
> 7 42 LOAD_GLOBAL 5 (NULL + input) 54 LOAD_CONST 2 (' masukan cookie : ') 56 PRECALL 1 60 CALL 1 70 STORE_FAST 0 (cookie)
> 
> 8 72 NOP
> 
> 9 74 LOAD_GLOBAL 6 (ses) 86 LOAD_METHOD 4 (get) 108 LOAD_CONST 3 ('https://business.facebook.com/business_locations') 110 LOAD_CONST 4 ('Mozilla/5.0 (Linux; Android 8.1.0; MI 8 Build/OPM1.171019.011) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.86 Mobile Safari/537.36') 112 LOAD_CONST 5 ('https://www.facebook.com/') 114 LOAD_CONST 6 ('business.facebook.com') 116 LOAD_CONST 7 ('https://business.facebook.com') 118 LOAD_CONST 8 ('1') 120 LOAD_CONST 9 ('id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7') 122 LOAD_CONST 10 ('max-age=0') 124 LOAD_CONST 11 ('text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,_/_;q=0.8') 126 LOAD_CONST 12 ('text/html; charset=utf-8') 128 LOAD_CONST 13 (('user-agent', 'referer', 'host', 'origin', 'upgrade-insecure-requests', 'accept-language', 'cache-control', 'accept', 'content-type')) 130 BUILD_CONST_KEY_MAP 9 132 LOAD_CONST 14 ('cookie') 134 LOAD_FAST 0 (cookie) 136 BUILD_MAP 1 138 KW_NAMES 15 140 PRECALL 3 144 CALL 3 154 STORE_FAST 1 (data)
> 
> 10 156 LOAD_GLOBAL 11 (NULL + re) 168 LOAD_ATTR 6 (search) 178 LOAD_CONST 16 ('(EAAG\w+)') 180 LOAD_FAST 1 (data) 182 LOAD_ATTR 7 (text) 192 PRECALL 2 196 CALL 2 206 STORE_FAST 2 (find_token)
> 
> 11 208 LOAD_GLOBAL 17 (NULL + open) 220 LOAD_CONST 17 ('token.txt') 222 LOAD_CONST 18 ('w') 224 PRECALL 2 228 CALL 2 238 LOAD_METHOD 9 (write) 260 LOAD_FAST 2 (find_token) 262 LOAD_METHOD 10 (group) 284 LOAD_CONST 19 (1) 286 PRECALL 1 290 CALL 1 300 PRECALL 1 304 CALL 1 314 POP_TOP
> 
> 12 316 LOAD_GLOBAL 17 (NULL + open) 328 LOAD_CONST 20 ('cookie.txt') 330 LOAD_CONST 18 ('w') 332 PRECALL 2 336 CALL 2 346 LOAD_METHOD 9 (write) 368 LOAD_FAST 0 (cookie) 370 PRECALL 1 374 CALL 1 384 POP_TOP
> 
> 13 386 LOAD_GLOBAL 23 (NULL + menu) 398 PRECALL 0 402 CALL 0 412 POP_TOP 414 LOAD_CONST 0 (None) 416 RETURN_VALUE >> 418 PUSH_EXC_INFO
> 
> 14 420 POP_TOP
> 
> 15 422 LOAD_GLOBAL 1 (NULL + os) 434 LOAD_ATTR 1 (system) 444 LOAD_CONST 21 ('rm token.txt cookie.txt') 446 PRECALL 1 450 CALL 1 460 POP_TOP
> 
> 16 462 LOAD_GLOBAL 25 (NULL + exit) 474 LOAD_CONST 22 (' login gagal kemungkinan cookie invalid atau tumbal mati') 476 PRECALL 1 480 CALL 1 490 POP_TOP 492 POP_EXCEPT 494 LOAD_CONST 0 (None) 496 RETURN_VALUE >> 498 COPY 3 500 POP_EXCEPT 502 RERAISE 1 ExceptionTable: 74 to 412 -> 418 [0] 418 to 490 -> 498 [1] lasti
> 
> Disassembly of <code object menu at 0x7666936400, file "", line 19>: 19 0 RESUME 0
> 
> 20 2 NOP
> 
> 21 4 LOAD_GLOBAL 1 (NULL + open) 16 LOAD_CONST 1 ('token.txt') 18 LOAD_CONST 2 ('r') 20 PRECALL 2 24 CALL 2 34 LOAD_METHOD 1 (read) 56 PRECALL 0 60 CALL 0 70 STORE_FAST 0 (token)
> 
> 22 72 LOAD_GLOBAL 1 (NULL + open) 84 LOAD_CONST 3 ('cookie.txt') 86 LOAD_CONST 2 ('r') 88 PRECALL 2 92 CALL 2 102 LOAD_METHOD 1 (read) 124 PRECALL 0 128 CALL 0 138 STORE_FAST 1 (cok)
> 
> 23 140 LOAD_CONST 4 ('cookie') 142 LOAD_FAST 1 (cok) 144 BUILD_MAP 1 146 STORE_FAST 2 (cookie)
> 
> 24 148 LOAD_GLOBAL 4 (ses) 160 LOAD_METHOD 3 (get) 182 LOAD_CONST 5 ('https://graph.facebook.com/me?fields=name&access_token=') 184 LOAD_FAST 0 (token) 186 FORMAT_VALUE 0 188 BUILD_STRING 2 190 LOAD_FAST 2 (cookie) 192 KW_NAMES 6 194 PRECALL 2 198 CALL 2 208 LOAD_METHOD 4 (json) 230 PRECALL 0 234 CALL 0 244 LOAD_CONST 7 ('name') 246 BINARY_SUBSCR 256 STORE_FAST 3 (nama) 258 JUMP_FORWARD 21 (to 302) >> 260 PUSH_EXC_INFO
> 
> 25 262 POP_TOP
> 
> 26 264 LOAD_GLOBAL 11 (NULL + login) 276 PRECALL 0 280 CALL 0 290 POP_TOP 292 POP_EXCEPT 294 JUMP_FORWARD 3 (to 302) >> 296 COPY 3 298 POP_EXCEPT 300 RERAISE 1
> 
> 27 >> 302 LOAD_GLOBAL 13 (NULL + print) 314 LOAD_CONST 8 (' selamat datang ') 316 LOAD_FAST 3 (nama) 318 FORMAT_VALUE 0 320 LOAD_CONST 9 (', silahkan pakai sesuka hati') 322 BUILD_STRING 3 324 PRECALL 1 328 CALL 1 338 POP_TOP
> 
> 28 340 LOAD_GLOBAL 15 (NULL + input) 352 LOAD_CONST 10 (' masukan link : ') 354 PRECALL 1 358 CALL 1 368 STORE_FAST 4 (idt)
> 
> 29 370 LOAD_GLOBAL 17 (NULL + int) 382 LOAD_GLOBAL 15 (NULL + input) 394 LOAD_CONST 11 (' masukan limit : ') 396 PRECALL 1 400 CALL 1 410 PRECALL 1 414 CALL 1 424 STORE_FAST 5 (limit)
> 
> 30 426 NOP
> 
> 31 428 LOAD_CONST 12 (0) 430 STORE_FAST 6 (n)
> 
> 32 432 LOAD_CONST 13 ('graph.facebook.com') 434 LOAD_CONST 14 ('max-age=0') 436 LOAD_CONST 15 ('?0') 438 LOAD_CONST 16 ('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.66 Safari/537.36') 440 LOAD_CONST 17 (('authority', 'cache-control', 'sec-ch-ua-mobile', 'user-agent')) 442 BUILD_CONST_KEY_MAP 4 444 STORE_FAST 7 (header)
> 
> 33 446 LOAD_GLOBAL 19 (NULL + range) 458 LOAD_GLOBAL 17 (NULL + int) 470 LOAD_FAST 5 (limit) 472 PRECALL 1 476 CALL 1 486 PRECALL 1 490 CALL 1 500 GET_ITER >> 502 FOR_ITER 109 (to 722) 504 STORE_FAST 8 (x)
> 
> 34 506 LOAD_FAST 6 (n) 508 LOAD_CONST 18 (1) 510 BINARY_OP 13 (+=) 514 STORE_FAST 6 (n)
> 
> 35 516 LOAD_GLOBAL 4 (ses) 528 LOAD_METHOD 10 (post) 550 LOAD_CONST 19 ('https://graph.facebook.com/v16.0/me/feed?link=') 552 LOAD_FAST 4 (idt) 554 FORMAT_VALUE 0 556 LOAD_CONST 20 ('&published=0&access_token=') 558 LOAD_FAST 0 (token) 560 FORMAT_VALUE 0 562 BUILD_STRING 4 564 LOAD_FAST 7 (header) 566 LOAD_FAST 2 (cookie) 568 KW_NAMES 21 570 PRECALL 3 574 CALL 3 584 LOAD_ATTR 11 (text) 594 STORE_FAST 9 (post)
> 
> 36 596 LOAD_GLOBAL 9 (NULL + json) 608 LOAD_ATTR 12 (loads) 618 LOAD_FAST 9 (post) 620 PRECALL 1 624 CALL 1 634 STORE_FAST 10 (data)
> 
> 37 636 LOAD_CONST 22 ('id') 638 LOAD_FAST 9 (post) 640 CONTAINS_OP 0 642 POP_JUMP_FORWARD_IF_FALSE 23 (to 690)
> 
> 38 644 LOAD_GLOBAL 13 (NULL + print) 656 LOAD_CONST 23 (' ') 658 LOAD_FAST 6 (n) 660 FORMAT_VALUE 0 662 LOAD_CONST 24 ('. berhasil membagikan ') 664 LOAD_FAST 5 (limit) 666 FORMAT_VALUE 0 668 LOAD_CONST 25 (" ['id']") 670 BUILD_STRING 5 672 PRECALL 1 676 CALL 1 686 POP_TOP 688 JUMP_BACKWARD 94 (to 502)
> 
> 40 >> 690 LOAD_GLOBAL 27 (NULL + exit) 702 LOAD_CONST 26 (' gagal membagikan, kemungkinan token invalid') 704 PRECALL 1 708 CALL 1 718 POP_TOP 720 JUMP_BACKWARD 110 (to 502)
> 
> 33 >> 722 LOAD_CONST 0 (None) 724 RETURN_VALUE >> 726 PUSH_EXC_INFO
> 
> 41 728 POP_TOP
> 
> 42 730 LOAD_GLOBAL 27 (NULL + exit) 742 LOAD_CONST 26 (' gagal membagikan, kemungkinan token invalid') 744 PRECALL 1 748 CALL 1 758 POP_TOP 760 POP_EXCEPT 762 LOAD_CONST 0 (None) 764 RETURN_VALUE >> 766 COPY 3 768 POP_EXCEPT 770 RERAISE 1 ExceptionTable: 4 to 256 -> 260 [0] 260 to 290 -> 296 [1] lasti 428 to 720 -> 726 [0] 726 to 758 -> 766 [1] lasti

too long, it will waste time, Youtube can teach you
